### PR TITLE
Fix kong keycloak

### PR DESCRIPTION
**Pull request by obdulia-losantos**
you don't need to merge this, but it's another way to create the realms, my problem with this is that I cannot connect to keycloak using the admin client. :disappointed_relieved: 

`KC_URL="http://localhost:8080/keycloak/auth/"` ???

### CODE REVIEW

**Comment by shawnsarwar** [comment]
Either of these should work depending on the source.
From in the docker-net
`KC_INTERNAL=http://keycloak:8080/keycloak/auth/`
Via Kong
`KC_PUBLIC=http://aether.local/keycloak/auth/`

**Comment by obdulia-losantos** [comment]
```
Failed to send request - Connect to aether.local:80 [aether.local/127.0.0.1] failed: Connection refused (Connection refused)
```
:sob:

**Comment by shawnsarwar** [comment]
`http://aether.local/keycloak/auth/` should be available if you've run initialize_docker_environment and then turned on kong & keycloak via docker-compose.

**Comment by obdulia-losantos** [comment]
@shawnsarwar now you can merge it into your branch if you want to :sweat_smile:

**Pull request merged**
